version: '3.8'

services:
  
  # PostgreSQL Database

  postgres:
    image: postgres:16-alpine
    container_name: meteorisk_db
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: meteorisk
    ports:
      - "5434:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-db/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U airflow -d meteorisk"]
      interval: 5s
      timeout: 5s
      retries: 5

  
  # Airflow Webserver (UI)
  
  airflow-webserver:
    build:
      context: .
      dockerfile: Dockerfile.airflow
    container_name: meteorisk_airflow_web
    restart: always
    depends_on:
      postgres:
        condition: service_healthy
    environment:
     #=================================== databasetype+username password:airflow@host:port/database
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres:5432/meteorisk
      AIRFLOW__CORE__LOAD_EXAMPLES: 'false'
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__WEBSERVER__SECRET_KEY: meteorisk_secret_key_1234
    volumes:
      - ./dags:/opt/airflow/dags
      - ./data:/opt/airflow/data
      - ./src:/opt/airflow/src
    ports:
      - "8080:8080"
    command: >
      bash -c "airflow db migrate &&
               airflow users create --username admin --password admin --firstname Meteo --lastname Risk --role Admin --email admin@meteorisk.ma || true &&
               airflow webserver"

  
  # Airflow Scheduler
  
  airflow-scheduler:
    build:
      context: .
      dockerfile: Dockerfile.airflow
    container_name: meteorisk_airflow_scheduler
    restart: always
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres:5432/meteorisk
      AIRFLOW__CORE__LOAD_EXAMPLES: 'false'
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
    volumes:
      - ./dags:/opt/airflow/dags
      - ./data:/opt/airflow/data
      - ./src:/opt/airflow/src
    command: airflow scheduler

  
  # Streamlit Dashboard
  
  streamlit:
    build:
      context: .
      dockerfile: Dockerfile.streamlit
    container_name: meteorisk_streamlit
    restart: always
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./streamlit:/app
      - ./data:/app/data
    ports:
      - "8501:8501"

volumes:
  postgres_data: